import json

restaurants = [
    {"name": "Ichiran Ramen Dotonbori", "category": "Ramen", "area": "Dotonbori", "description": "Famous tonkotsu ramen chain", "price_range": "¥1,000-2,000", "highlights": "24/7 service"},
    {"name": "Kani Doraku", "category": "Seafood", "area": "Dotonbori", "description": "Iconic crab restaurant", "price_range": "¥3,000-8,000", "highlights": "Giant mechanical crab sign"},
    {"name": "Kushikatsu Daruma", "category": "Kushikatsu", "area": "Shinsekai", "description": "Famous deep-fried skewers", "price_range": "¥2,000-4,000", "highlights": "No double dipping!"},
    {"name": "Okonomiyaki Mizuno", "category": "Okonomiyaki", "area": "Dotonbori", "description": "Traditional Osaka pancake shop", "price_range": "¥1,200-2,500", "highlights": "Since 1945"},
    {"name": "Takoyaki Juhachiban", "category": "Takoyaki", "area": "Dotonbori", "description": "Popular octopus balls", "price_range": "¥500-1,000", "highlights": "Crispy outside"},
    {"name": "Menya 7.5Hz", "category": "Ramen", "area": "Namba", "description": "Award-winning ramen", "price_range": "¥1,000-1,500", "highlights": "Rich broth"},
    {"name": "Yakiniku M", "category": "Yakiniku", "area": "Namba", "description": "Premium Japanese BBQ", "price_range": "¥5,000-10,000", "highlights": "Wagyu beef"},
    {"name": "Sushi Zanmai", "category": "Sushi", "area": "Namba", "description": "Fresh sushi restaurant", "price_range": "¥2,000-5,000", "highlights": "Good value"},
    {"name": "Tempura Endo", "category": "Tempura", "area": "Umeda", "description": "High-quality tempura", "price_range": "¥3,000-6,000", "highlights": "Fresh seafood"},
    {"name": "Udon Yoshino", "category": "Udon", "area": "Namba", "description": "Traditional udon noodles", "price_range": "¥800-1,500", "highlights": "Hand-made"},
    {"name": "Ippudo Ramen", "category": "Ramen", "area": "Umeda", "description": "Hakata-style ramen", "price_range": "¥1,000-1,500", "highlights": "Tonkotsu broth"},
    {"name": "Gindaco Takoyaki", "category": "Takoyaki", "area": "Namba", "description": "Chain takoyaki shop", "price_range": "¥600-1,200", "highlights": "Consistent quality"},
    {"name": "Rikuro Cheesecake", "category": "Dessert", "area": "Namba", "description": "Famous fluffy cheesecake", "price_range": "¥300-500", "highlights": "Jiggly texture"},
    {"name": "Fukushige", "category": "Oden", "area": "Shinsekai", "description": "Historic oden shop", "price_range": "¥2,000-4,000", "highlights": "Since 1923"},
    {"name": "Bizenya Izakaya", "category": "Izakaya", "area": "Namba", "description": "Traditional Japanese pub", "price_range": "¥3,000-5,000", "highlights": "Local atmosphere"},
    {"name": "Menya Takemura", "category": "Ramen", "area": "Tennouji", "description": "Shoyu ramen specialist", "price_range": "¥900-1,400", "highlights": "Clear broth"},
    {"name": "Kaiten Sushi Kuroshio", "category": "Sushi", "area": "Kuromon Market", "description": "Conveyor belt sushi", "price_range": "¥2,000-4,000", "highlights": "Fresh from market"},
    {"name": "Soba Yoshino", "category": "Soba", "area": "Umeda", "description": "Buckwheat noodles", "price_range": "¥1,000-2,000", "highlights": "Hand-made soba"},
    {"name": "Gyukatsu Motomura", "category": "Beef Cutlet", "area": "Namba", "description": "Fried beef cutlet", "price_range": "¥1,500-2,500", "highlights": "Cook yourself"},
    {"name": "Sushi Iwa", "category": "Sushi", "area": "Yodoyabashi", "description": "High-end sushi", "price_range": "¥15,000-25,000", "highlights": "Edomae style"},
    {"name": "Ramen Haruki", "category": "Ramen", "area": "Shinsaibashi", "description": "Miso ramen specialist", "price_range": "¥900-1,300", "highlights": "Rich miso"},
    {"name": "Tempura Tenmatsu", "category": "Tempura", "area": "Namba", "description": "Traditional tempura", "price_range": "¥4,000-8,000", "highlights": "Seasonal vegetables"},
    {"name": "Yakiniku Ten", "category": "Yakiniku", "area": "Umeda", "description": "Premium BBQ", "price_range": "¥6,000-12,000", "highlights": "A5 wagyu"},
    {"name": "Udon Maruka", "category": "Udon", "area": "Dotonbori", "description": "Self-service udon", "price_range": "¥500-1,000", "highlights": "Quick and cheap"},
    {"name": "Kushikatsu Yaekatsu", "category": "Kushikatsu", "area": "Namba", "description": "Deep-fried skewers", "price_range": "¥2,000-3,500", "highlights": "Variety pack"},
    {"name": "Takoyaki Wanaka", "category": "Takoyaki", "area": "Dotonbori", "description": "Popular takoyaki stand", "price_range": "¥500-800", "highlights": "Crispy texture"},
    {"name": "Tonkatsu Maisen", "category": "Tonkatsu", "area": "Umeda", "description": "Pork cutlet specialist", "price_range": "¥2,000-4,000", "highlights": "Premium pork"},
    {"name": "Izakaya Tachinomi", "category": "Izakaya", "area": "Namba", "description": "Standing bar", "price_range": "¥2,000-4,000", "highlights": "Local vibe"},
    {"name": "Okonomiyaki Yukari", "category": "Okonomiyaki", "area": "Umeda", "description": "Osaka pancake shop", "price_range": "¥1,200-2,500", "highlights": "Modan-yaki"},
    {"name": "Sushi Kappo", "category": "Sushi", "area": "Kitashinchi", "description": "Sushi and kappo", "price_range": "¥8,000-15,000", "highlights": "Fresh daily"},
    {"name": "Yakitori Torimatsu", "category": "Yakitori", "area": "Tennouji", "description": "Grilled chicken skewers", "price_range": "¥3,000-5,000", "highlights": "Charcoal grilled"},
    {"name": "Soba Kiriya", "category": "Soba", "area": "Shinsaibashi", "description": "Fresh soba noodles", "price_range": "¥1,200-2,200", "highlights": "Cold soba"},
    {"name": "Ramen Menya Saimi", "category": "Ramen", "area": "Nakazakicho", "description": "Shio ramen", "price_range": "¥900-1,400", "highlights": "Light salt broth"},
    {"name": "Tempura Mikuni", "category": "Tempura", "area": "Umeda", "description": "High-end tempura", "price_range": "¥8,000-15,000", "highlights": "Seasonal"},
    {"name": "Yakiniku Rokkasen", "category": "Yakiniku", "area": "Namba", "description": "All-you-can-eat BBQ", "price_range": "¥3,000-5,000", "highlights": "90 min course"},
    {"name": "Udon Hanamaru", "category": "Udon", "area": "Multiple", "description": "Self-service udon chain", "price_range": "¥400-800", "highlights": "Budget friendly"},
    {"name": "Kushikatsu Shinsekai", "category": "Kushikatsu", "area": "Shinsekai", "description": "Traditional kushikatsu", "price_range": "¥2,000-4,000", "highlights": "Old school"},
    {"name": "Sushi Saito", "category": "Sushi", "area": "Yodoyabashi", "description": "Premium sushi", "price_range": "¥20,000-35,000", "highlights": "Reservation needed"},
    {"name": "Takoyaki Kukuru", "category": "Takoyaki", "area": "Dotonbori", "description": "Takoyaki restaurant", "price_range": "¥800-1,500", "highlights": "Various toppings"},
    {"name": "Tonkatsu Katsukura", "category": "Tonkatsu", "area": "Near Kyoto", "description": "Famous tonkatsu", "price_range": "¥2,000-3,500", "highlights": "Kurobuta pork"},
    {"name": "Torikizoku", "category": "Yakitori", "area": "Multiple", "description": "Affordable yakitori", "price_range": "¥1,500-3,000", "highlights": "Budget-friendly"},
    {"name": "Sushiya no Nohachi", "category": "Sushi", "area": "Kitashinchi", "description": "Traditional sushi", "price_range": "¥8,000-15,000", "highlights": "Omakase"},
    {"name": "Yakitori Heian", "category": "Yakitori", "area": "Tsuruhashi", "description": "Grilled skewers", "price_range": "¥2,500-4,500", "highlights": "Korean town"},
    {"name": "Kaiseki Kikunoi", "category": "Kaiseki", "area": "Higashiyama", "description": "Traditional multi-course", "price_range": "¥15,000-30,000", "highlights": "3 Michelin stars"},
    {"name": "Ramen Ippudo", "category": "Ramen", "area": "Dotonbori", "description": "Famous ramen chain", "price_range": "¥1,000-1,500", "highlights": "Shiromaru"},
    {"name": "Sushi Zanmai Namba", "category": "Sushi", "area": "Namba", "description": "24-hour sushi", "price_range": "¥2,500-6,000", "highlights": "Open 24/7"},
    {"name": "Hajime", "category": "French/Japanese", "area": "Yodoyabashi", "description": "3 Michelin star restaurant", "price_range": "¥20,000+", "highlights": "Innovative cuisine"},
    {"name": "Okonomiyaki Chibo", "category": "Okonomiyaki", "area": "Dotonbori", "description": "Multi-floor restaurant", "price_range": "¥1,500-3,000", "highlights": "Soul food"},
    {"name": "Tsuruhashi Fugetsu", "category": "Okonomiyaki", "area": "Tsuruhashi", "description": "Okonomiyaki chain", "price_range": "¥1,000-2,000", "highlights": "DIY option"},
    {"name": "Sushiya Nohachi", "category": "Sushi", "area": "Kitashinchi", "description": "Traditional sushi counter", "price_range": "¥10,000-18,000", "highlights": "Premium fish"}
]

with open('osaka_restaurants.json', 'w', encoding='utf-8') as f:
    json.dump(restaurants, f, ensure_ascii=False, indent=2)

print(f"✓ Saved {len(restaurants)} restaurants to osaka_restaurants.json")